import 'package:ala_saree3/core/widgets/app_button.dart';
import 'package:ala_saree3/core/widgets/loading_indicator.dart';
import 'package:ala_saree3/presentation/screens/checkout/widgets/checkout_item_card.dart';
import 'package:ala_saree3/presentation/screens/checkout/widgets/checkout_total_row.dart';
import 'package:ala_saree3/presentation/screens/checkout/widgets/pill_row.dart';
import 'package:ala_saree3/presentation/screens/checkout/widgets/section_title.dart';
import 'package:ala_saree3/presentation/screens/checkout/widgets/shipping_address_card.dart';
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:provider/provider.dart';
import '../../../core/routing/app_router.dart';
import '../../../domain/entities/order.dart';
import '../../../domain/entities/order_status.dart';
import '../../controller/cart_provider.dart';
import '../../controller/order_provider.dart';
import 'payment_success_dialog.dart';

class CheckoutScreen extends StatefulWidget {
  const CheckoutScreen({super.key});

  @override
  State<CheckoutScreen> createState() => _CheckoutScreenState();
}

class _CheckoutScreenState extends State<CheckoutScreen> {
  String? _name;
  String? _address;
  String? _phone;

  Future<void> _onAddAddressPressed() async {
    final result = await context.push<Map<String, String>?>(
      AppRouter.addAddress,
    );

    if (result != null) {
      setState(() {
        _name =
            result['name']?.trim().isEmpty == true
                ? _name
                : result['name'] ?? _name;
        _address = result['address'] ?? _address;
        _phone = result['phone'] ?? _phone;
      });
    }
  }

  /// Places an order from the current cart items.
  /// Creates an Order entity and calls the OrderProvider to place it.
  Future<void> _placeOrder(BuildContext context) async {
    final cart = context.read<CartProvider>();
    final orderProvider = context.read<OrderProvider>();

    if (cart.items.isEmpty) {
      return;
    }

    // Show loading indicator
    showDialog<void>(
      context: context,
      barrierDismissible: false,
      builder: (context) => LoadingIndicator(),
    );

    try {
      // Create order from cart items
      final order = Order(
        id: '', // Will be generated by repository
        items: cart.items,
        totalPrice: cart.totalPrice,
        orderStatus: OrderStatus.pending,
        createdAt: DateTime.now(),
      );

      // Place the order
      final createdOrder = await orderProvider.placeOrder(order);

      // Close loading dialog
      if (context.mounted) {
        Navigator.of(context).pop();

        if (createdOrder != null) {
          // Clear cart after successful order
          cart.clear();

          // Show success dialog
          await showDialog<void>(
            context: context,
            barrierDismissible: false,
            builder: (_) => const PaymentSuccessDialog(),
          );
        } else {
          // Show error if order failed
          if (context.mounted) {
            ScaffoldMessenger.of(context).showSnackBar(
              SnackBar(
                content: Text(orderProvider.error ?? 'Failed to place order'),
                backgroundColor: Theme.of(context).colorScheme.error,
              ),
            );
          }
        }
      }
    } catch (e) {
      // Close loading dialog
      if (context.mounted) {
        Navigator.of(context).pop();
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Error placing order: ${e.toString()}'),
            backgroundColor: Theme.of(context).colorScheme.error,
          ),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final cart = context.watch<CartProvider>();
    final items = cart.items;
    final colorScheme = Theme.of(context).colorScheme;

    return Scaffold(
      backgroundColor: colorScheme.surface,
      appBar: AppBar(
        backgroundColor: colorScheme.surface,
        elevation: 0,
        foregroundColor: colorScheme.onSurface,
        centerTitle: true,
        title: const Text(
          'CHECKOUT',
          style: TextStyle(letterSpacing: 2, fontWeight: FontWeight.w500),
        ),
      ),
      body:
          items.isEmpty
              ? const Center(
                child: Text(
                  'Your cart is empty',
                  style: TextStyle(fontSize: 16),
                ),
              )
              : ListView(
                padding: const EdgeInsets.symmetric(
                  horizontal: 24,
                  vertical: 16,
                ),
                children: [
                  const SectionTitle('SHIPPING ADDRESS'),
                  const SizedBox(height: 8),
                  ShippingAddressCard(
                    name: _name ?? 'Iris Watson',
                    address:
                        _address ??
                        '606-3727 Ullamcorper. Street\nRoseville NH 11523',
                    phone: _phone ?? '(786) 713-8616',
                    onAddPressed: _onAddAddressPressed,
                  ),
                  const SizedBox(height: 16),
                  const SectionTitle('SHIPPING METHOD'),
                  const SizedBox(height: 8),
                  PillRow(
                    label: 'Pickup at store',
                    trailing: 'FREE',
                    onTap: () {
                      _showSimpleSheet(
                        context,
                        title: 'Shipping method',
                        options: const [
                          'Pickup at store',
                          'Standard delivery',
                          'Express delivery',
                        ],
                      );
                    },
                  ),
                  const SizedBox(height: 16),
                  const SectionTitle('PAYMENT METHOD'),
                  const SizedBox(height: 8),
                  PillRow(
                    label: 'Select payment method',
                    trailing: '',
                    onTap: () {
                      context.push(AppRouter.addCard);
                    },
                  ),
                  const SizedBox(height: 8),
                  const Divider(),
                  const SizedBox(height: 8),
                  // Order summary (simple)
                  ...items.map((item) => CheckoutItemCard(item: item)),
                  const SizedBox(height: 24),
                  CheckoutTotalRow(totalPrice: cart.totalPrice),
                  const SizedBox(height: 24),
                  AppButton(
                    onPressed: () async {
                      await _placeOrder(context);
                    },
                    text: 'PLACE ORDER',
                    enabled: items.isNotEmpty,
                  ),
                ],
              ),
      // bottomNavigationBar: SizedBox(
      //   width: 150,
      //   child: AppButton(
      //     onPressed: () async {
      //       await _placeOrder(context);
      //     },
      //     text: 'PLACE ORDER',
      //     enabled: items.isNotEmpty,
      //   ),
      // ),
    );
  }
}

void _showSimpleSheet(
  BuildContext context, {
  required String title,
  required List<String> options,
}) {
  showModalBottomSheet<void>(
    context: context,
    shape: const RoundedRectangleBorder(
      borderRadius: BorderRadius.vertical(top: Radius.circular(16)),
    ),
    builder: (ctx) {
      final colorScheme = Theme.of(ctx).colorScheme;
      return SafeArea(
        child: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Center(
                child: Container(
                  width: 40,
                  height: 4,
                  margin: const EdgeInsets.only(bottom: 12),
                  decoration: BoxDecoration(
                    color: colorScheme.outlineVariant,
                    borderRadius: BorderRadius.circular(2),
                  ),
                ),
              ),
              Text(
                title,
                style: const TextStyle(
                  fontSize: 14,
                  fontWeight: FontWeight.w600,
                ),
              ),
              const SizedBox(height: 8),
              ...options.map(
                (opt) => ListTile(
                  contentPadding: EdgeInsets.zero,
                  title: Text(opt),
                  onTap: () => Navigator.of(ctx).pop(),
                ),
              ),
            ],
          ),
        ),
      );
    },
  );
}
